Add 3D (ZCYX) parsing for MolecularDevices datasets
fmi-faim/faim-hcs pull request #5
Opened 2023-02-16 12:54 UTC by imagejan

2023-02-21 09:33 UTC, tibuch requested changes
- [ ] add test for `get_well_image_ZCYX`
- [x] expose montage functions
- [ ] add test for stage-montage function
- [ ] add improved test-data

2023-03-02 19:30 UTC, imagejan commented on src/faim_hcs/io/MolecularDevicesImageXpress.py
> +                    row["path"] = str(Path(root).joinpath(f))
Does `joinpath` have any advantages compared to the slash operator? I find the operator more readable and concise.

2023-03-03 13:43 UTC, imagejan commented on src/faim_hcs/MetaSeriesUtils.py
> +            [hist1.combine(hist2) for hist1, hist2 in zip(channel_histograms, ch_hists)]
Fixed with https://github.com/fmi-faim/faim-hcs/commit/783ea179c0731b5bc9f5b6a59885940e8e8178a1.

2023-03-06 16:24 UTC, tibuch commented on tests/test_Zarr.py
> +            / "C03_empty_histogram.npz"  # TODO why?
If we want to aggregate histograms later on we can assume that all of them exist. Even if they are empty.

2023-03-06 16:27 UTC, tibuch commented on src/faim_hcs/MetaSeriesUtils.py
> +                ch_metadata  # FIXME we take he last occurrence here, should be the first one
Why? Is there some metadata which is affected by first vs last?

2023-03-06 16:32 UTC, tibuch commented on tests/test_Zarr.py
> +            / "C03_empty_histogram.npz"  # TODO why?
Okay, got it! The test is just wrong! Great catch!

2023-03-07 10:56 UTC, imagejan commented
Thanks for your latest fixes, @tibuch.

I squashed the wip commits and force-pushed. This PR looks good to merge now, in my opinion (provided the tests pass on CI as well).

2023-03-07 12:03 UTC, tibuch commented
I agree. I am just finalizing the example notebooks and then it is good to go!

2023-03-08 14:09 UTC, tibuch approved these changes

2023-03-08 14:10 UTC, merged